logging:
  level:
    web: DEBUG
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: test20412041
    password: bkcmseqrdvbdxzvr
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true